version: "3.8"

services:
  app:
    build: .
    command: >
      /bin/sh -c "alembic -c src/alembic.ini upgrade head && uvicorn src.main:app --reload --proxy-headers --host 0.0.0.0 --port ${APP_CONTAINER_PORT} --workers 4"
    restart: always
    volumes:
      - ./:/backend
    ports:
      - "${APP_HOST_PORT}:${APP_CONTAINER_PORT}"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - ./.env.dev.db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server --requirepass "${REDIS_PASS}"
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  flower:
    build: .
    command: celery -A src.config.celery_app flower --port=${FLOWER_HOST_PORT}
    ports:
      - "${FLOWER_HOST_PORT}:${FLOWER_CONTAINER_PORT}"
    env_file:
      - ./.env.dev
    depends_on:
      - app
      - redis
      - worker

  worker:
    build: .
    command: celery -A src.config.celery_app worker --loglevel=info
    volumes:
      - ./:/backend
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - app
      - redis

  scheduler:
    build: .
    command: celery -A src.config.celery_app beat --loglevel=info
    volumes:
      - ./:/backend
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - app
      - redis

  minio:
    image: minio/minio:latest
    command: server --console-address ":${MINIO_CONSOLE_PORT}" /data/
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    env_file:
      - ./.env.dev
    volumes:
      - ./minio-storage:/data
