version: "3.8"

services:
  app:
    build: .
    command: >
      /bin/sh -c "alembic -c src/alembic.ini upgrade head && uvicorn src.main:app --reload --proxy-headers --host 0.0.0.0 --port 8000 --workers 4"
    restart: always
    volumes:
      - ./:/backend
    ports:
      - "8001:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev.db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A src.config.celery_app worker --loglevel=info
    volumes:
      - ./:/backend
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - app
      - redis

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./.env.dev
    volumes:
      - minio-storage:/data

volumes:
  minio-storage: