"""add pictureLink complete

Revision ID: 1e7f44122f60
Revises: c05886e8005b
Create Date: 2024-08-29 20:54:33.566149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e7f44122f60"
down_revision: Union[str, None] = "c05886e8005b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "achievement", sa.Column("pictureLinkComplete", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("achievement", "pictureLinkComplete")
    # ### end Alembic commands ###
