"""fix user sub type

Revision ID: 63ba0ba3c593
Revises: bc0db5558a68
Create Date: 2024-08-25 14:54:32.161376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63ba0ba3c593"
down_revision: Union[str, None] = "bc0db5558a68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_subscription_type_fkey", "user", type_="foreignkey")
    op.create_foreign_key(
        None, "user", "subscription", ["subscription_type"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.create_foreign_key(
        "user_subscription_type_fkey",
        "user",
        "subscription",
        ["subscription_type"],
        ["id"],
    )
    # ### end Alembic commands ###
