"""add set null field

Revision ID: bc0db5558a68
Revises: 909d0853853d
Create Date: 2024-08-25 14:31:08.714343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc0db5558a68"
down_revision: Union[str, None] = "909d0853853d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bill_sub_type_fkey", "bill", type_="foreignkey")
    op.create_foreign_key(
        None, "bill", "subscription", ["sub_type"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bill", type_="foreignkey")
    op.create_foreign_key(
        "bill_sub_type_fkey", "bill", "subscription", ["sub_type"], ["id"]
    )
    # ### end Alembic commands ###
