"""add field for feedback

Revision ID: c05886e8005b
Revises: d74217e5cbd4
Create Date: 2024-08-29 15:50:54.004412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c05886e8005b"
down_revision: Union[str, None] = "d74217e5cbd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("is_feedback_complete", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_feedback_complete")
    # ### end Alembic commands ###
