"""add sub expitation time

Revision ID: d068fcd53f5e
Revises: b2e9ddb43314
Create Date: 2024-08-20 16:31:02.482315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d068fcd53f5e"
down_revision: Union[str, None] = "b2e9ddb43314"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("subscription_expired", sa.DateTime(), nullable=True)
    )
    op.drop_constraint(
        "user_achievement_achievement_id_fkey", "user_achievement", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "user_achievement",
        "achievement",
        ["achievement_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_achievement", type_="foreignkey")
    op.create_foreign_key(
        "user_achievement_achievement_id_fkey",
        "user_achievement",
        "achievement",
        ["achievement_id"],
        ["id"],
    )
    op.drop_column("user", "subscription_expired")
    # ### end Alembic commands ###
