"""add alter fields

Revision ID: d74217e5cbd4
Revises: 63ba0ba3c593
Create Date: 2024-08-25 16:45:37.253432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d74217e5cbd4"
down_revision: Union[str, None] = "63ba0ba3c593"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription", sa.Column("promocode", sa.String(), nullable=True))
    op.add_column("subscription", sa.Column("promo_price", sa.Integer(), nullable=True))
    op.add_column(
        "subscription", sa.Column("promo_price_str", sa.String(), nullable=True)
    )
    op.add_column("subscription", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "user", sa.Column("is_connected_to_telegram", sa.Boolean(), nullable=True)
    )
    op.add_column("user", sa.Column("promo", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "promo")
    op.drop_column("user", "is_connected_to_telegram")
    op.drop_column("subscription", "is_active")
    op.drop_column("subscription", "promo_price_str")
    op.drop_column("subscription", "promo_price")
    op.drop_column("subscription", "promocode")
    # ### end Alembic commands ###
