"""edit topics

Revision ID: f16dd74df34e
Revises: 0de1c8616097
Create Date: 2024-07-07 12:36:25.516974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16dd74df34e'
down_revision: Union[str, None] = '0de1c8616097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopic', sa.Column('topic_title', sa.String(), nullable=True))
    op.drop_constraint('subtopic_topic_id_fkey', 'subtopic', type_='foreignkey')
    op.create_foreign_key(None, 'subtopic', 'topic', ['topic_title'], ['title'])
    op.drop_column('subtopic', 'topic_id')
    op.add_column('word', sa.Column('subtopic', sa.String(), nullable=True))
    op.create_foreign_key(None, 'word', 'subtopic', ['subtopic'], ['title'])
    op.create_foreign_key(None, 'word', 'topic', ['topic'], ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_column('word', 'subtopic')
    op.add_column('subtopic', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subtopic', type_='foreignkey')
    op.create_foreign_key('subtopic_topic_id_fkey', 'subtopic', 'topic', ['topic_id'], ['id'])
    op.drop_column('subtopic', 'topic_title')
    # ### end Alembic commands ###
