name: CI

on:
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:


jobs:
  CI:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9

    - name: Cache virtualenv
      uses: actions/cache@v3
      with:
        key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version}}-${{ hashFiles('requirements.txt') }}
        path: .venv

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Run linters
      run: |
        python -m black ./src --check

    - name: Run tests
      env:
        ENV: ${{ secrets.TEST_ENV }}
        GOOGLE_CREDENTIALS: ${{ secrets.TEST_GOOGLE_CREDENTIALS }}
      run: |
        echo "$ENV" > .env
        echo "$GOOGLE_CREDENTIALS" > ./src/config/json_configs/google_credentials.json
        python -m pytest -p no:warnings -o log_cli=true
